### ISSUE TITLE
Support Moshi as an optional JSON parser

### ISSUE THREAD

**Issue by yogurtearl** [optimizely/java-sdk#391]
Optimizely supports multiple optional JSON parsers. 
https://github.com/optimizely/java-sdk/blob/12acebad6c5574fa4e57662306c4d4701ee15fbd/core-api/build.gradle#L9

Moshi is a popular JSON parser, especially on Android. 
https://github.com/square/moshi

Please add optional support for moshi.

**Comment by The-inside-man** [comment]
After careful review of the following issue/request, our team has determined that in order to move forward, we would kindly ask for a submission on the following page, carefully outlining what is being requested. This allows our team to work your request into our backlog of items. This is usually a result of current work load, priority tasks, size of request, etc. We appreciate your cooperation and understanding.

Please submit here: https://experimentation.ideas.aha.io/
